#!/usr/bin/env bash
git_log()
{
	git config --global alias.lg "log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --left-right"
	echo -e "\033[0;33m git lg"
}

git_log "$@"

